### ISSUE TITLE
No GIF outputting

### ISSUE THREAD

**Issue by wakeupmrkim** [NathanRutzky/Generate-GIF#1]
Hi! Thanks for putting this awesome tool together. I've followed all the steps but it doesn't output an actual gif in my directory. Any advice? I'm on Sketch 3.

![2](https://cloud.githubusercontent.com/assets/1189159/4411662/abbf73f6-44f0-11e4-8ef6-62ea0042adcc.png)

**Comment by ClintGreive** [comment]
No output on Version 3.2.2 (9983). I've also followed @NathanRutzky steps mentioned in 26 Sept post with no success. Can't wait for fix release! :)

**Comment by kbastien** [comment]
@NathanRutzky when can we expect the next release? Thanks for being awesome!

**Comment by NathanRutzky** [comment]
@kbastien Hopefully within the next week. I just pushed an update for  [Generate ICNS.](https://github.com/NathanRutzky/Generate-ICNS) This is next in line. Thanks for your patience!
